# https://alacritty.org/config-alacritty.html
import = [
    "~/.config/alacritty/themes/dracula_plus.toml"
]


[shell]
program = "/usr/bin/zsh"


[env]
TERM="xterm-256color"

[window]
# startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
blur = false

padding = { x = 0, y = 0 }
# HACK: this fixes weird spacing at the bottom
dynamic_padding = true
opacity = 0.8


[mouse]
hide_when_typing = true


[cursor]
style = "Block"


[keyboard]
bindings = [
  { key = "N", mods = "Control", action = "SpawnNewInstance" },
  { key = "F11", action = "ToggleFullscreen" }
]


[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }

size = 14
builtin_box_drawing = true
