# https://alacritty.org/config-alacritty.html
import = [
    "~/.config/alacritty/themes/dracula_plus.toml"
]


[shell]
program = "/usr/bin/zsh"


[window]
# startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
blur = false

padding = { x = 0, y = 0 }
# HACK: this fixes weird spacing at the bottom
dynamic_padding = true
opacity = 0.8


[mouse]
hide_when_typing = true


[cursor]
style = "Block"


[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]


[font]
normal = { family = "Hack Nerd Font"}
size = 16
builtin_box_drawing = true
